url: https://leilisysbio.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Lei Li
email: leili.bioinfo@gmail.com
description: "Lei Li - Github Page"

# Color settings (hex-codes without the leading hash-tag)
color:
primary: fed136
secondary: fec503
secondary-dark: 333

# Team names, titles and social links
people:
- name: Lei Li
pic: img/about/lei.png
position: Postdoc @ IMIB, Germany
social:
- title: twitter
  url: https://twitter.com/LeiLi_bioinfo
- title: github
  url: http://leilisysbio.github.io/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
- title: twitter
  url: https://twitter.com/LeiLi_bioinfo
- title: github
  url: http://leilisysbio.github.io/

# Postal address (add as many lines as necessary)
address:
- line: Josef-Schneider-Straße 2 / Bau D15,
- line: 97080 Würzburg, Germany

# Build settings
markdown: kramdown
permalink: pretty
