url: https://lei.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Lei Li
email: leili.bioinfo@gmail.com
description: "Lei Li - Github Page"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Lei Li
  pic: img/about/hanfang.png
  position: Postdoc @ Institute for Molecular Infection Biology, University of Würzburg
  social:
  - title: twitter
    url: https://twitter.com/LeiLi_bioinfo
  #- title: linkedin
  #  url:  https://www.linkedin.com/in/hfang15
  - title: github
    url: https://github.com/LeiLiSysBio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/LeiLi_bioinfo
  #- title: linkedin
  #  url:  https://www.linkedin.com/in/hfang15
  - title: github
    url: https://github.com/LeiLiSysBio

# Postal address (add as many lines as necessary)
address:
  - line: Josef-Schneider-Straße 2 / Bau D15
  - line: 97080 Würzburg

# Build settings
markdown: kramdown
permalink: pretty
